version: '2'

services:
    nodeapp:
        container_name : node-app
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - './app/:/app'
            - /app/node_modules
        ports:
            - "9090:5000"
        networks:
            - my-app-net
        env_file:
            - ./.env
    mongodb:
        image: mongo:4.4
        ports:
            - '27017:27017'
        networks:
            - my-app-net
        deploy:
            replicas: 1
        volumes:
            - /home/mongodb_data:/data/db
            - /home/mongod.conf:/etc/mongod.conf
    redis:
        image: redislabs/redisearch
        volumes:
            - /home/redis_data:/data
        networks:
            - my-app-net
networks:
    my-app-net:
        driver: bridge
        ipam:
            config:
            - subnet: "20.1.0.0/16"
